Generate a mock pillar if no pillar already exists
For convenience generate a mock pillar if no pillar already exists to
allow for the execution of zero configuration test builds.

diff --git a/gentoo-bootstrap/salt/salt-state-copy b/gentoo-bootstrap/salt/salt-state-copy
--- a/gentoo-bootstrap/salt/salt-state-copy
+++ b/gentoo-bootstrap/salt/salt-state-copy
@@ -1,8 +1,26 @@
 #!/bin/bash
+#
+# Prepare the packer salt build by collecting salt states. This is done to
+# manage the desired folder structure. All states listed in the init.sls file
+# and gentoo folder at the root of the project are included.
+#
+# This script is using a YAML parser for Python (dev-python/pyyaml) to read the
+# init.sls file. My version of salt has a dependency on pyyaml so this works at
+# the moment with little effort.
+#
+# For convenience a mock pillar is generated if no pillar already exists. This
+# has the potential to allow for the execution of zero configuration test
+# builds.
+#
 
 set -u
 
-SALT_DIR=build/salt
+#
+# copy salt states into build
+#
+
+BUILD=build
+SALT_DIR=${BUILD}/salt
 read -r -d '' DOTFILES_INCLUDE <<'EOF'
 import yaml
 
@@ -28,3 +46,73 @@ cp ../init.sls "${SALT_DIR}/dotfiles/"
 
 echo "gentoo"
 cp --recursive ../gentoo "${SALT_DIR}/gentoo"
+
+#
+# generate pillar if needed
+#
+
+if [ ! -f salt/pillar.asc ] && [ ! -d salt/pillar ]; then
+   echo "[WARN] Generating mock salt/pillar"
+   OLD_UMASK="$(umask)"
+   umask 077
+   SALT_KEYS="$(mktemp -d)" && trap "rm -r \"$SALT_KEYS\"" EXIT
+
+   # The mock salt/pillar.asc key uses %transient-key to generate keys faster
+   # along with %no-protection to skip passphrase. This key is not for general
+   # use. Salt does require no passphrase as it works in a non-interactive
+   # mode.
+   SALT_KEYS_GPG="${SALT_KEYS}/gpg"
+   mkdir "$SALT_KEYS_GPG"
+   gpg --quiet --homedir "$SALT_KEYS_GPG" --batch --generate-key 2>/dev/null <<-'EOF'
+	Key-Type: default
+	Subkey-Type: default
+	Name-Real: salt-master
+	Name-Comment: mock key
+	Expire-Date: 0
+	%no-protection
+	%transient-key
+	%commit
+	EOF
+   gpg --quiet --homedir "$SALT_KEYS_GPG" --export-secret-keys --armor > salt/pillar.asc
+
+   # The mock salt/pillar contains a transient SSH private key (id_rsa) with an
+   # empty passphrase for unattended key generation. Even though it is
+   # encrypted to test salt.renderers.gpg it is not for general use.
+   mkdir --parents salt/pillar
+   cat > salt/pillar/top.sls <<-'EOF'
+	base:
+	  '*':
+	    - dotfiles.ssh
+	EOF
+   SALT_KEYS_SSH="${SALT_KEYS}/ssh"
+   mkdir "$SALT_KEYS_SSH"
+   ssh-keygen -q -t rsa -N '' -f "${SALT_KEYS_SSH}"/id_rsa
+   gpg --quiet --homedir "$SALT_KEYS_GPG" --encrypt --recipient salt-master --armor "${SALT_KEYS_SSH}"/id_rsa
+   IDENTITY=$(<"${SALT_KEYS_SSH}"/id_rsa.asc)
+   print_identity() {
+      echo ".ssh/${1}/id_rsa: |"
+      echo "$IDENTITY" | sed 's/^/  /'
+   }
+   mkdir --parents salt/pillar/dotfiles/ssh
+   cat > salt/pillar/dotfiles/ssh/init.sls <<-EOF
+	#!yaml|gpg
+
+	$(print_identity bitbucket)
+	$(print_identity github)
+	$(print_identity visualstudio)
+	EOF
+   umask "$OLD_UMASK"
+fi
+
+if [ ! -f salt/pillar.asc ]; then
+   (>&2 echo "A pillar GPG key (salt/pillar.asc) is required" \
+             "but a mock pillar key was not generated because salt/pillar" \
+             "already exists.")
+   exit 1
+fi
+
+if [ ! -d salt/pillar ]; then
+   (>&2 echo "A pillar (salt/pillar) is required but a mock pillar was not" \
+             "generated because GPG key salt/pillar.asc already exists.")
+   exit 1
+fi
