Simplify initramfs
Remove '/usr/bin' from PATH, the generated initramfs doesn't currently
have any /usr/bin. It was originally added along with cryptsetup, maybe
something has changed since and it's no longer needed or was it always
unused?

Remove unused `cat` program, although not used in the init script it was
likely included to help with recovery if a command failed leaving us at
the shell. cat could, for example, print the init script so the commands
could be referenced for debugging and manual execution. For this use
case Bash builtins could be used, e.g. `echo "$(<init)"`.

Remove static device nodes from initramfs, these devices are already
being created by the kernel through devtmpfs.

Improve boot times when waiting for the root device. The init script
used to always wait 3 seconds to let the root device settle but will now
try to look for it in three attempts with a 1 second delay between each
attempt. This improves the best case where the device is available and
no delay would be needed.

Consolidate error checking and give error messages a little more
context.

diff --git a/kernel/initramfs.init b/kernel/initramfs.init
--- a/kernel/initramfs.init
+++ b/kernel/initramfs.init
@@ -1,38 +1,34 @@
 #!/bin/bash
 
-export PATH="/sbin:/bin:/usr/bin"
-
-echo -n "Waiting for devices..."
-sleep 3
+export PATH='/sbin:/bin'
 
 mount -t proc none /proc
 mount -t sysfs none /sys
 mount -t devtmpfs none /dev
 mount -t tmpfs tmpfs /run
 
-device="$(/sbin/blkid --uuid "$LUKS_UUID")"
-
-cryptsetup isLuks "$device"
-if [ "$?" -ne 0 ]; then
-   echo "Error: $device is not an encrypted device."
+echo 'Waiting for devices...'
+for try in {1..3}; do
+   luks_device="$(blkid --uuid "$LUKS_UUID")" && break
+   sleep 1
+done
+if [ -z "$luks_device" ]; then
+   echo "Error: Failed to find encrypted device 'UUID=${LUKS_UUID}'."
    exec bash
 fi
 
-cryptsetup open --allow-discards --key-file /etc/key "$device" linux-lvm
-if [ "$?" -ne 0 ]; then
-   echo "Error: Failed to open encrypted device."
+if ! cryptsetup open --allow-discards --key-file /etc/key "$luks_device" linux-lvm; then
+   echo "Error: Failed to open encrypted device '${luks_device}'."
    exec bash
 fi
 
-lvm vgchange --activate y "$ROOT_VOLUME_GROUP"
-if [ "$?" -ne 0 ]; then
-   echo "Error: Failed to start LVM."
+if ! lvm vgchange --activate y "$ROOT_VOLUME_GROUP"; then
+   echo 'Error: Failed to start LVM.'
    exec bash
 fi
 
-mount /new-root
-if [ "$?" -ne 0 ]; then
-   echo "Error: Mount root failed."
+if ! mount /new-root; then
+   echo 'Error: Mount root failed.'
    exec bash
 fi
 
